# Generated by Django 6.0.5 on 2026-05-13 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseViewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Kurs ko'rish tarixi",
                'verbose_name_plural': "Kurs ko'rish tarixlari",
                'db_table': 'course_view_history',
                'indexes': [models.Index(fields=['user'], name='course_view_user_id_64e1fb_idx'), models.Index(fields=['course'], name='course_view_course__00b2ef_idx'), models.Index(fields=['created_at'], name='course_view_created_f964f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlillar',
                'db_table': 'favorites',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('view', "Ko'rish"), ('favorite', "Sevimlilarga qo'shish"), ('review', 'Sharh qoldirish'), ('comment', 'Izoh qoldirish'), ('purchase', 'Sotib olish')], max_length=25)),
                ('metadata', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi faoliyati',
                'verbose_name_plural': 'Foydalanuvchi faoliyatlari',
                'db_table': 'user_activities',
                'indexes': [models.Index(fields=['user'], name='user_activi_user_id_260c6d_idx'), models.Index(fields=['activity_type'], name='user_activi_activit_534635_idx'), models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx')],
            },
        ),
    ]
