# Generated by Django 6.0.5 on 2026-05-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseviewhistory',
            options={'ordering': ['-created_at'], 'verbose_name': "Kurs ko'rish tarixi", 'verbose_name_plural': "Kurs ko'rish tarixlari"},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sevimli', 'verbose_name_plural': 'Sevimlillar'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi faoliyati', 'verbose_name_plural': 'Foydalanuvchi faoliyatlari'},
        ),
    ]
