# Generated by Django 6.0.5 on 2026-05-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sharh', 'verbose_name_plural': 'Sharhlar'},
        ),
        migrations.AlterModelOptions(
            name='reviewmedia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sharh media', 'verbose_name_plural': 'Sharh medialari'},
        ),
        migrations.AlterModelOptions(
            name='reviewvote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sharh ovozi', 'verbose_name_plural': 'Sharh ovozlari'},
        ),
    ]
