# Generated by Django 6.0.5 on 2026-05-13 15:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(upload_to='category_icons/')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'categories',
                'indexes': [models.Index(fields=['slug'], name='categories_slug_b4303a_idx'), models.Index(fields=['name'], name='categories_name_98d7d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='course_center_logos/')),
                ('website', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "O'quv markaz",
                'verbose_name_plural': "O'quv markazlari",
                'db_table': 'course_centers',
                'indexes': [models.Index(fields=['slug'], name='course_cent_slug_c6deb3_idx'), models.Index(fields=['title'], name='course_cent_title_f2ecca_idx'), models.Index(fields=['verified'], name='course_cent_verifie_352723_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kurs tegi',
                'verbose_name_plural': 'Kurs teglari',
                'db_table': 'course_tags',
                'indexes': [models.Index(fields=['name'], name='course_tags_name_8129b1_idx'), models.Index(fields=['slug'], name='course_tags_slug_2b8a9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='mentor_avatars/')),
                ('experience', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=255)),
                ('instagram_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentorlar',
                'db_table': 'mentors',
                'indexes': [models.Index(fields=['full_name'], name='mentors_full_na_85fefe_idx'), models.Index(fields=['slug'], name='mentors_slug_f60b3d_idx'), models.Index(fields=['specialization'], name='mentors_special_02a043_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich daraja"), ('middle', "O'rta daraja"), ('pro', 'Pro daraja'), ('bootcamp', 'Bootcamp')], max_length=25)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_in_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('certificate_available', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
                ('course_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursecenter')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.mentor')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseTagItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='courses.course')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.coursetag')),
            ],
            options={
                'verbose_name': 'Kurs tegi elementi',
                'verbose_name_plural': 'Kurs tegi elementlari',
                'db_table': 'course_tag_items',
                'unique_together': {('course', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_slug_360be0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['title'], name='courses_title_0466cc_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_categor_2870c7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['mentor'], name='courses_mentor__ee4ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_center'], name='courses_course__79bf26_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['average_rating'], name='courses_average_f67875_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price'], name='courses_price_56bbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='courses_created_0aa93c_idx'),
        ),
    ]
