# Generated by Django 6.0.5 on 2026-05-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(error_messages="Kurs haqida qisqacha ta'rif yozish majburiy"),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='coursecenter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='course_center_logos/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_avatars/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
