# Generated by Django 6.0.5 on 2026-05-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_icon_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(error_messages={'message': "Kurs haqida qisqacha ta'rif yozish majburiy"}),
        ),
    ]
