# Generated by Django 6.0.5 on 2026-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(error_messages={'blank': "Kurs haqida qisqacha ta'rif yozish majburiy"}),
        ),
    ]
