# Generated by Django 6.0.5 on 2026-05-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='coursecenter',
            options={'ordering': ['-created_at'], 'verbose_name': "O'quv markaz", 'verbose_name_plural': "O'quv markazlari"},
        ),
        migrations.AlterModelOptions(
            name='coursetag',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs tegi', 'verbose_name_plural': 'Kurs teglari'},
        ),
        migrations.AlterModelOptions(
            name='coursetagitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs tegi elementi', 'verbose_name_plural': 'Kurs tegi elementlari'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentorlar'},
        ),
    ]
