# Generated by Django 6.0.5 on 2026-05-13 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('delete', "O'chirish"), ('suspend', "To'xtatish"), ('restore', 'Qayta tiklash'), ('warn', 'Ogohlanish')], max_length=25)),
                ('reason', models.TextField()),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Moderatsiya amali',
                'verbose_name_plural': 'Moderatsiya amalları',
                'db_table': 'moderation_actions',
                'indexes': [models.Index(fields=['moderator'], name='moderation__moderat_b5120b_idx'), models.Index(fields=['action'], name='moderation__action_b11c47_idx'), models.Index(fields=['created_at'], name='moderation__created_05f00e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Tekshirilayotgan'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('resolved', 'Hal qilingan')], default='pending', max_length=25)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'db_table': 'reports',
                'indexes': [models.Index(fields=['status'], name='reports_status_e83c1d_idx'), models.Index(fields=['created_at'], name='reports_created_c5f642_idx')],
            },
        ),
    ]
